spring:
  application:
    name: techbridge-aitutorial
  profiles:
    # Profile ----------------------------------------
    active: ${SPRING_PROFILES_ACTIVE:dev}
  # ------------------------------------------------
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: none
  jackson:
    default-property-inclusion: NON_NULL
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
  mail:
    host: smtp.upm.es
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        from: ${MAIL_USERNAME}
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      # 1. PARTE DE VALIDACIÓN (Resource Server)
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/api/techbridge-user/oauth2/jwks
      # 2. PARTE DE CLIENTE (Para Feign / AuthorizedClientService)
      client:
        registration:
          internal-client:
            client-id: internal-api-client
            client-secret: internal-secret
            provider: "internal-provider"
            authorization-grant-type: client_credentials
            scope: profile
        provider:
          internal-provider:
            token-uri: http://localhost:8080/api/techbridge-user/oauth2/token
server:
  port: 8083
  forward-headers-strategy: framework

info:
  app:
    artifact: "@project.artifactId@"
    version: "@project.version@"
    build: "@maven.build.timestamp@"
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    es.upm: DEBUG
    org.springframework.security: WARN

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

app:
  ai:
    limits:
      global-max: 3
      global-warning: 2
      user-max: 3
      admin-email: "jiale.wang@alumnos.upm.es"